site_name: LimaCharlie.io
repo_url: https://github.com/refractionPOINT/lce_doc
site_description: Official documentation for LimaCharlie.io
docs_dir: 'docs'
markdown_extensions:
    - toc:
        permalink: True
    - fenced_code
theme: readthedocs
pages:
    - Home: index.md
    - Quick Start: lcc_quick_start.md
    - Installation Keys: manage_keys.md
    - Deploying Sensors: deploy_sensor.md
    - Outputs: outputs.md
    - API Keys: api_keys.md
    - Sensor Commands: sensor_commands.md
    - Tagging: tagging.md
    - Detection & Response: dr.md
    - Add-ons: user_addons.md
    - Replicants: replicants.md
    - Replay: replay.md
    - Events: events.md
    - ID Schemes: agentid.md
    - FAQ: faq.md
    - Upgrading: upgrading.md
    - Troubleshooting: troubleshooting.md
    - Updating: update_org.md
    - User Control: user_access.md
    - Error Codes: errors.md
extra_css: [extra.css]
